#!/bin/bash -l
#
#$ -N MP2
#$ -pe smp 10
#$ -cwd 

#qsub -R y -mods l_hard m_mem_free 16G
mkdir -p files_dat/
export LD_PRELOAD=/FMOPhore/QM_runs/lib/libgfortran.so.3
/FMOPhore/QM_runs/rungms input.inp 01 10 >& output.log
mv *dat files_dat/.
find . -size 0 -delete
